server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          hmac-secret: "${JWT_SECRET:dev-secret}"
          access-ttl: 30m
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
