version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: planroom-redis
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    environment:
      - TZ=UTC
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: planroom-redis-commander
    ports:
      - "8081:8081"
    environment:
      # name:host:port:db:password
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redisdata:

