name: CI - Build & Test
on:
  push:
    branches: ["**"]
  pull_request:
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Grant execute permissions for Gradle wrapper
        if: hashFiles('gradlew') != ''
        run: chmod +x gradlew
      - name: Build & test (Gradle)
        if: hashFiles('gradlew') != ''
        run: ./gradlew --no-daemon clean test
      - name: Assemble JAR (Gradle)
        if: hashFiles('gradlew') != ''
        run: ./gradlew --no-daemon bootJar
      - name: Build & test (Maven)
        if: hashFiles('pom.xml') != ''
        run: mvn -B -DskipITs=false -DskipTests=false clean verify
      - name: Upload build artifacts (JARs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: |
            **/build/libs/*.jar
            **/target/*.jar
          if-no-files-found: warn
